force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>This is used to consistently import data to a version of the SDO and translate data into other languages.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Institution_Type__c.field-meta.xml
<CustomField>
    <fullName>Institution_Type__c</fullName>
    <description>Shows whether this HCP is a Doctor or a Polyclinic/Clinic, or whether this HCO is a Hospital/Contract.</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Polyclinic</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
                <isActive>false</isActive>
                <label>Government</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>University</fullName>
                <isActive>false</isActive>
                <label>University</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Institution_HCO.recordType-meta.xml
<RecordType>
    <fullName>Institution_HCO</fullName>
    <active>true</active>
    <label>HCO</label>
</RecordType>

force-app/main/default/classes/ClinicHcpSubtypeBatch.cls
/**
 * Ensures CLINIC-* practice sites use Institution_HCO + Subtype Clinic.
 */
public class ClinicHcpSubtypeBatch implements Database.Batchable<SObject>, Database.Stateful {
  public Integer updatedCount = 0;

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      [
        SELECT Id, RecordTypeId, Institution_Type__c
        FROM Account
        WHERE External_ID__c LIKE 'CLINIC-%' AND IsPersonAccount = FALSE
      ]
    );
  }

  public void execute(Database.BatchableContext bc, List<Account> scope) {
    Id clinicRt = AccountMasterImportUtil.clinicHcpRecordTypeId();
    for (Account account : scope) {
      account.RecordTypeId = clinicRt;
      if (String.isBlank(account.Institution_Type__c)) {
        account.Institution_Type__c = 'Clinic';
      }
    }
    Database.DmlOptions opts = new Database.DmlOptions();
    opts.duplicateRuleHeader.allowSave = true;
    opts.optAllOrNone = false;
    for (Database.SaveResult result : Database.update(scope, opts)) {
      if (result.isSuccess()) {
        updatedCount++;
      }
    }
  }

  public void finish(Database.BatchableContext bc) {
    System.debug(LoggingLevel.INFO, 'ClinicHcpSubtypeBatch updated=' + updatedCount);
  }
}