force-app/main/default/objects/Account_Affiliation__c/Account_Affiliation__c.object-meta.xml
<CustomObject>
    <label>Account Affiliation</label>
    <nameField>
        <displayFormat>AFF-{00000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Territory_Fields__c/Account_Territory_Fields__c.object-meta.xml
<CustomObject>
    <label>Account Territory Fields</label>
    <nameField>
        <displayFormat>ATF-{00000}</displayFormat>
        <label>Account Territory Fields Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territory Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Territory_Fields__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Territory Fields</relationshipLabel>
    <relationshipName>Account_Territory_Fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Territory_Product_Fields__c/Account_Territory_Product_Fields__c.object-meta.xml
<CustomObject>
    <label>Account Territory Product Fields</label>
    <nameField>
        <displayFormat>ATPF-{00000}</displayFormat>
        <label>Account Territory Product Fields Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territory Product Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Territory_Product_Fields__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Territory Product Fields</relationshipLabel>
    <relationshipName>Account_Territory_Product_Fields</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brick_Pharmacy__c/Brick_Pharmacy__c.object-meta.xml
<CustomObject>
    <label>Brick Pharmacy</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Brick Pharmacy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brick Pharmacies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Medical Inquiries</relationshipLabel>
    <relationshipName>Medical_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Presentation_Session__c/CLM_Presentation_Session__c.object-meta.xml
<CustomObject>
    <label>CLM Presentation Session</label>
    <nameField>
        <displayFormat>CLMS-{00000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CLM Presentation Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_Presentation_Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CLM Sessions</relationshipLabel>
    <relationshipName>CLM_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Presentation_Session__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>CLM Sessions</relationshipLabel>
    <relationshipName>CLM_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Time_Card_Account_Target__c/Employee_Time_Card_Account_Target__c.object-meta.xml
<CustomObject>
    <label>Employee Time Card Account Target</label>
    <nameField>
        <displayFormat>ETCAT-{00000}</displayFormat>
        <label>Account Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Time Card Account Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Time_Card_Account_Target__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Card Account Targets</relationshipLabel>
    <relationshipName>Time_Card_Account_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Time_Card_Account_Target__c/fields/Account_Territory_Fields__c.field-meta.xml
<CustomField>
    <fullName>Account_Territory_Fields__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Territory Fields</label>
    <referenceTo>Account_Territory_Fields__c</referenceTo>
    <relationshipLabel>Time Card Account Targets</relationshipLabel>
    <relationshipName>Time_Card_Account_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Meeting_Locations_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Location__c/Meeting_Location__c.object-meta.xml
<CustomObject>
    <label>Meeting Location</label>
    <nameField>
        <displayFormat>ML-{00000}</displayFormat>
        <label>Meeting Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meeting Locations</relationshipLabel>
    <relationshipName>Meeting_Location_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Meeting Locations</relationshipLabel>
    <relationshipName>Meeting_Location_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pharma_Project_Account_Goal__c/Pharma_Project_Account_Goal__c.object-meta.xml
<CustomObject>
    <label>Pharma Project Account Goal</label>
    <nameField>
        <label>Account Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharma Project Account Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pharma_Project_Account_Goal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Pharma_Project_Account_Goals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pharmacy_Sales_Withdrawal__c/Pharmacy_Sales_Withdrawal__c.object-meta.xml
<CustomObject>
    <label>Pharmacy Sales Withdrawal</label>
    <nameField>
        <displayFormat>PSW-{00000}</displayFormat>
        <label>Pharmacy Sales Withdrawal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pharmacy Sales Withdrawals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Speakers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>VST-{00000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Attendee__c/Visit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Visit Attendee</label>
    <nameField>
        <displayFormat>VA-{00000}</displayFormat>
        <label>Visit Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Attendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visit Attendances</relationshipLabel>
    <relationshipName>Visit_Attendances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Attendee__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visit Attendees</relationshipLabel>
    <relationshipName>Visit_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Product_Survey_Feedback__c/Visit_Product_Survey_Feedback__c.object-meta.xml
<CustomObject>
    <label>Visit Product Survey Feedback</label>
    <nameField>
        <displayFormat>VPSF-{00000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Product Survey Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Product_Survey_Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Product Survey Feedbacks</relationshipLabel>
    <relationshipName>Account_Product_Survey_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Product_Survey_Feedback__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Product Survey Feedbacks</relationshipLabel>
    <relationshipName>Product_Survey_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountWipeBatch.cls
/**
 * Deletes Account affiliations, common Account children, then Accounts.
 * Chained phases via finish().
 */
public without sharing class AccountWipeBatch implements Database.Batchable<SObject>, Database.Stateful {
    public static final String PHASE_AFFILIATIONS = 'AFFILIATIONS';
    public static final String PHASE_ATF = 'ATF';
    public static final String PHASE_ATP = 'ATP';
    public static final String PHASE_VISIT_FEEDBACK = 'VISIT_FEEDBACK';
    public static final String PHASE_VISIT_ATTENDEES = 'VISIT_ATTENDEES';
    public static final String PHASE_VISITS = 'VISITS';
    public static final String PHASE_BRICK_PHARMACY = 'BRICK_PHARMACY';
    public static final String PHASE_WITHDRAWALS = 'WITHDRAWALS';
    public static final String PHASE_ACCOUNT_GOALS = 'ACCOUNT_GOALS';
    public static final String PHASE_TIME_CARD_TARGETS = 'TIME_CARD_TARGETS';
    public static final String PHASE_MEETING_LOCATIONS = 'MEETING_LOCATIONS';
    public static final String PHASE_SPEAKERS = 'SPEAKERS';
    public static final String PHASE_CLM_SESSIONS = 'CLM_SESSIONS';
    public static final String PHASE_LOCATIONS = 'LOCATIONS';
    public static final String PHASE_CASES = 'CASES';
    public static final String PHASE_OPPORTUNITIES = 'OPPORTUNITIES';
    public static final String PHASE_ACCOUNTS = 'ACCOUNTS';

    private String currentPhase;
    private Integer successCount = 0;
    private Integer errorCount = 0;
    private List<String> errorSamples = new List<String>();

    public AccountWipeBatch() {
        this(PHASE_AFFILIATIONS);
    }

    public AccountWipeBatch(String phase) {
        this.currentPhase = phase;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        if (currentPhase == PHASE_AFFILIATIONS) {
            return Database.getQueryLocator('SELECT Id FROM Account_Affiliation__c');
        }
        if (currentPhase == PHASE_ATF) {
            return Database.getQueryLocator('SELECT Id FROM Account_Territory_Fields__c');
        }
        if (currentPhase == PHASE_ATP) {
            return Database.getQueryLocator('SELECT Id FROM Account_Territory_Product_Fields__c');
        }
        if (currentPhase == PHASE_VISIT_FEEDBACK) {
            return Database.getQueryLocator('SELECT Id FROM Visit_Product_Survey_Feedback__c');
        }
        if (currentPhase == PHASE_VISIT_ATTENDEES) {
            return Database.getQueryLocator('SELECT Id FROM Visit_Attendee__c');
        }
        if (currentPhase == PHASE_VISITS) {
            return Database.getQueryLocator('SELECT Id FROM Visit__c');
        }
        if (currentPhase == PHASE_BRICK_PHARMACY) {
            return Database.getQueryLocator('SELECT Id FROM Brick_Pharmacy__c');
        }
        if (currentPhase == PHASE_WITHDRAWALS) {
            return Database.getQueryLocator('SELECT Id FROM Pharmacy_Sales_Withdrawal__c');
        }
        if (currentPhase == PHASE_ACCOUNT_GOALS) {
            return Database.getQueryLocator('SELECT Id FROM Pharma_Project_Account_Goal__c');
        }
        if (currentPhase == PHASE_TIME_CARD_TARGETS) {
            return Database.getQueryLocator('SELECT Id FROM Employee_Time_Card_Account_Target__c');
        }
        if (currentPhase == PHASE_MEETING_LOCATIONS) {
            return Database.getQueryLocator('SELECT Id FROM Meeting_Location__c');
        }
        if (currentPhase == PHASE_SPEAKERS) {
            return Database.getQueryLocator('SELECT Id FROM Speaker__c');
        }
        if (currentPhase == PHASE_CLM_SESSIONS) {
            return Database.getQueryLocator('SELECT Id FROM CLM_Presentation_Session__c');
        }
        if (currentPhase == PHASE_LOCATIONS) {
            return Database.getQueryLocator('SELECT Id FROM Location__c WHERE Account__c != null');
        }
        if (currentPhase == PHASE_CASES) {
            return Database.getQueryLocator('SELECT Id FROM Case WHERE AccountId != null');
        }
        if (currentPhase == PHASE_OPPORTUNITIES) {
            return Database.getQueryLocator('SELECT Id, StageName, IsWon FROM Opportunity WHERE AccountId != null');
        }
        return Database.getQueryLocator('SELECT Id FROM Account');
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        if (currentPhase == PHASE_LOCATIONS) {
            for (SObject row : scope) {
                row.put('Account__c', null);
            }
            Database.SaveResult[] urs = Database.update(scope, false, AccessLevel.SYSTEM_MODE);
            tallySave(urs);
            return;
        }
        if (currentPhase == PHASE_OPPORTUNITIES) {
            for (SObject row : scope) {
                Opportunity o = (Opportunity) row;
                if (o.IsWon) {
                    o.StageName = 'Prospecting';
                }
            }
            Database.update(scope, false, AccessLevel.SYSTEM_MODE);
        }

        Database.DeleteResult[] results = Database.delete(scope, false, AccessLevel.SYSTEM_MODE);
        tallyDelete(results);
        List<Id> deletedIds = new List<Id>();
        for (Database.DeleteResult dr : results) {
            if (dr.isSuccess()) {
                deletedIds.add(dr.getId());
            }
        }
        if (!deletedIds.isEmpty()) {
            try {
                Database.emptyRecycleBin(deletedIds);
            } catch (Exception e) {
                // best-effort
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        String next = nextPhase(currentPhase);
        if (next != null) {
            Database.executeBatch(new AccountWipeBatch(next), 200);
        }
    }

    private static String nextPhase(String phase) {
        if (phase == PHASE_AFFILIATIONS) return PHASE_ATF;
        if (phase == PHASE_ATF) return PHASE_ATP;
        if (phase == PHASE_ATP) return PHASE_VISIT_FEEDBACK;
        if (phase == PHASE_VISIT_FEEDBACK) return PHASE_VISIT_ATTENDEES;
        if (phase == PHASE_VISIT_ATTENDEES) return PHASE_VISITS;
        if (phase == PHASE_VISITS) return PHASE_BRICK_PHARMACY;
        if (phase == PHASE_BRICK_PHARMACY) return PHASE_WITHDRAWALS;
        if (phase == PHASE_WITHDRAWALS) return PHASE_ACCOUNT_GOALS;
        if (phase == PHASE_ACCOUNT_GOALS) return PHASE_TIME_CARD_TARGETS;
        if (phase == PHASE_TIME_CARD_TARGETS) return PHASE_MEETING_LOCATIONS;
        if (phase == PHASE_MEETING_LOCATIONS) return PHASE_SPEAKERS;
        if (phase == PHASE_SPEAKERS) return PHASE_CLM_SESSIONS;
        if (phase == PHASE_CLM_SESSIONS) return PHASE_LOCATIONS;
        if (phase == PHASE_LOCATIONS) return PHASE_CASES;
        if (phase == PHASE_CASES) return PHASE_OPPORTUNITIES;
        if (phase == PHASE_OPPORTUNITIES) return PHASE_ACCOUNTS;
        return null;
    }

    private void tallySave(Database.SaveResult[] results) {
        if (results == null) {
            return;
        }
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                successCount++;
            } else {
                errorCount++;
                if (errorSamples.size() < 25) {
                    errorSamples.add(String.valueOf(sr.getErrors()));
                }
            }
        }
    }

    private void tallyDelete(Database.DeleteResult[] results) {
        if (results == null) {
            return;
        }
        for (Database.DeleteResult dr : results) {
            if (dr.isSuccess()) {
                successCount++;
            } else {
                errorCount++;
                if (errorSamples.size() < 25) {
                    String msg = dr.getErrors().isEmpty() ? 'delete failed' : dr.getErrors()[0].getMessage();
                    errorSamples.add(msg);
                }
            }
        }
    }
}